### ISSUE TITLE
 Crashes when near cactus and forestry hives

### ISSUE THREAD

**Issue by CrZain1000** [Arcaratus/BloodArsenal#77] opened 2016-10-14 19:55 UTC
Took out blood arsenal and it hasn't crashed so far, but something between baubles, forestry, blood arsenal, and cactus is having issues. And i also have the recommended forge version 12.18.2.2099 I don't know if that might cause an issues with you mod.

Crash Report: [crash-2016-10-14_09.20.14-server.txt](https://github.com/Arcaratus/BloodArsenal/files/529896/crash-2016-10-14_09.20.14-server.txt)
Crash Report: [crash-2016-10-14_09.49.55-server.txt](https://github.com/Arcaratus/BloodArsenal/files/529902/crash-2016-10-14_09.49.55-server.txt)

**Comment by TehNut** [comment] 2016-10-14 19:58
Dupe of #75

**Comment by CrZain1000** [comment] 2016-10-14 20:34
Ok, but thing is I never took any damage when the crash occurred. Anyways didn't realize it was already reported.

**Closed** 2016-10-15 01:36 UTC
Labels: duplicate
