### ISSUE TITLE
[Critical bug] Death type voids items from a player grave/corpse

### ISSUE THREAD

**Issue by Rubbertjuh** [Arcaratus/BloodArsenal#96] opened 2017-04-04 10:16 UTC
Author of Blood Magic says that it is somehow on Blood Arsenal's side, do you have any idea what may cause this?
On how to reproduce this please visit: https://github.com/WayofTime/BloodMagic/issues/1106

Thank you for your time

**Comment by Arcaratus** [comment] 2017-04-04 11:16
I am aware of the bug and it has already been fixed in my local version.

**Comment by Rubbertjuh** [comment] 2017-04-04 11:20
Ohhh that's awesome news! Any idea on when this local version will be pushed to github & released?

**Comment by Arcaratus** [comment] 2017-04-04 23:31
I have no clue about an ETA since I'm adding in major things to Blood Arsenal right now

**Comment by JadenDevon** [comment] 2017-06-03 16:27
I am having this problem on my server as well. Are you any closer to pushing the update?

**Comment by Arcaratus** [comment] 2017-07-09 20:05
Fixed in the latest version!

**Closed by Arcaratus** 2017-07-09 20:05 UTC

**Comment by EZKatnipz** [comment] 2017-07-24 02:24
anyway you could push this fix to the 1.10.2 version? Would be greatly appreciated.

**Comment by Arcaratus** [comment] 2017-07-25 15:48
A 1.10.2 version of Blood Arsenal is out now, which fixes the bug.

_Sent from my Samsung SM-G930T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Prime-Examples** [comment] 2019-01-16 04:56
I see that the issue is closed. I'm playing on 1.12.2 most current version of Blood magic and Blood arsenal. Dying to the glass sacrificial dagger. causes gravestone to void items.  I'm using GraveStone mod 1.12.2. I've done it by accident 3 times and reproduce it consistently. While standing next to altar, use glass sacrificial dagger till you die. The bug has occurred with and without using the incense altar before sacrificing.

**Comment by xAlicatt** [comment] 2019-01-16 08:04
@Arcaratus was coming to report that this issue has come up again recently, but see it has already been done. Just tagging you here to make sure that you see it.
