### ISSUE TITLE
Crash after clicking on Compact Master Stone with Transparent Orb

### ISSUE THREAD

**Issue by tethlah** [Arcaratus/BloodArsenal#17] opened 2015-06-23 23:50 UTC
When placing a Compact Master Ritual Stone from Blood Arsenal beneath a Master Ritual Stone from Blood magic and right clicking on the Compact Master Stone with a Transparent Orb from Blood Arsenal it will crash the entire client.  After that, You can't get back onto the server unless you have the server admin wipe your playerdata from from the server.

**Comment by Arcaratus** [comment] 2015-06-24 17:18
Do you have a log?

**Comment by tethlah** [comment] 2015-06-24 21:57
Here is the one from the guy who discovered it:  http://pastebin.com/20iqRvAj
Here is the one from my patch tester that verified it:  http://pastebin.com/uj5dChdK

And here is the one that the guy who discovered it got when he tried to reconnect:  http://pastebin.com/1NMifFb5

If you need some more, I could hop on and recreate it too.  I had so many error logs from various servers that I couldn't sort them out, but I can delete them and grab you another if you need it.

**Comment by Arcaratus** [comment] 2015-06-24 22:39
Hmm.. it's a Galacticraft incompatibility, lemme go check their code first.

**Comment by tethlah** [comment] 2015-06-25 12:15
Wish I could read these things, the more I try the more confusing it is.

**Comment by Arcaratus** [comment] 2015-06-25 16:49
I think..it's their problem, since it would seem to be the case for any Item that call the onUpdate() method would crash. Not entirely sure though, might want to report this issue to Galacticraft.

**Comment by tethlah** [comment] 2015-06-25 18:56
Why is it only these two blocks are affected.  We've extensively tested all 170 other mods in the pack, these two blocks are the only ones we have found to generate this error.  I will head over to the galactcraft guys and ask them about it though.  Could it possibly be an issue with PlayerAPI?

**Comment by Arcaratus** [comment] 2015-06-25 19:11
I don't think so. Unless PlayerAPI overrides the player updating.

**Comment by radfast** [comment] 2015-06-26 14:02
@Arcaratus I have looked at these crash reports and I do not believe this is a Galacticraft issue at all.  You are seeing a Galacticraft class in the stacktrace only because Galacticraft replaces the vanilla player entity, otherwise it would be vanilla EntityClientPlayerMP.onLivingUpdate() here.

To put this another way: this is no more a Galacticraft issue than it is an issue in vanilla Minecraft, and I don't think you would suggest this needs to be reported to Mojang!

Seems to me like the issue is in Alchemical Wizardry, not in your code, but these are the two things to look at:
> WayofTime.alchemicalWizardry.common.items.EnergyBattery.getCurrentEssence(EnergyBattery.java:203)
        at com.arc.bloodarsenal.items.orb.TransparentOrb.func_77663_a(TransparentOrb.java:48)

**Comment by tethlah** [comment] 2015-06-26 17:04
Well that would be blood magic right?

**Comment by Arcaratus** [comment] 2015-06-26 17:38
After contacting with Way, I believe I was using a deprecated method. (Although I can't seem to reproduce the crash anyhow) it should be fixed.

**Comment by tethlah** [comment] 2015-06-26 17:48
I have a dev server that I could send you the address to, you can come see what they set up and exactly how it crashed if you like.

**Comment by tethlah** [comment] 2015-06-29 02:04
Any word on when this will be fixed?  Our Ops are getting kicked out of the server left and right form a BloodArsenal null error with this:
at com.arc.bloodarsenal.items.block.PortableAltarBlock.addHiddenTooltip(PortableAltarBlock.java:39)

Any plans to release a fix or should I just remove it from the pack?

**Comment by Arcaratus** [comment] 2015-06-29 17:22
I'll release a fix later tomorrow, I'm removing all other possible conflicts with deprecated methods now.

**Comment by tethlah** [comment] 2015-06-29 17:24
Gotcha, I'll keep a lookout for it, maybe I can push the update to FTB before go live on the server Friday Morning.

**Comment by tethlah** [comment] 2015-07-01 15:38
Just curious, will there be an update today?  These crashes are far too often (we are talking several times a day).  If it's not possible to have an update by the end of the day I need to just remove the mod from our modpack (I'm getting dangerously close to go live)

**Comment by Arcaratus** [comment] 2015-07-01 19:27
Killing massive amounts of bugs the past hours, will try and get it out today.

**Comment by Arcaratus** [comment] 2015-07-01 19:30
Ok, literally just killed the last bug; I'm going to fix some things and then push a release.

**Comment by tethlah** [comment] 2015-07-02 03:25
Is it just blood arsenal or also blood magic?

**Comment by Arcaratus** [comment] 2015-07-02 14:45
It was my mod using a deprecated method of BM. You could say it was both I guess.

**Comment by tethlah** [comment] 2015-07-02 22:26
Now it's killing anyone in Creative mode.  Here's the log:

http://pastebin.com/zcm4RS0i

**Comment by tethlah** [comment] 2015-07-03 02:00
I've crashed 4 times in the last 2 hours!  Not being able to do things in creative mode as an OP on my own server sucks!

**Comment by Arcaratus** [comment] 2015-07-03 13:32
I have a feeling it's WAILA this time...

**Comment by tethlah** [comment] 2015-07-04 14:23
Well every single crash (that's 9 crashes in the last 24 hours!!!!!!)  all start with blood arsenal.

**Comment by Arcaratus** [comment] 2015-07-04 14:30
Try updating to the newest version

**Comment by tethlah** [comment] 2015-07-04 14:33
you updated again?

The log is posted above, it's the same stack trace every single time.

**Comment by Arcaratus** [comment] 2015-07-04 16:05
Still...?

**Comment by tethlah** [comment] 2015-07-04 16:08
Still what?  It can take up to 72 hours for FTB to upload my pack to the launcher, and it's completely random so it'll be a few days before we know for sure if the update you posted 2 hours ago will be working or not.

**Comment by Arcaratus** [comment] 2015-07-04 18:24
Oh, I thought you already tested to see if it still crashed with the latest.

**Comment by tethlah** [comment] 2015-07-06 02:21
Well, FTB put up the hotfix, not even an hour later:

http://pastebin.com/m8RYv0iH

**Comment by tethlah** [comment] 2015-07-06 02:22
Your mod doesn't generate anything when new chunks generate does it?

**Comment by Arcaratus** [comment] 2015-07-06 14:38
Nope

**Comment by tethlah** [comment] 2015-07-07 03:56
it's random when I have the NEI open it seams, maybe once out of 50 times or so.  What about chests, does your mod spawn items in chests anywhere?  Like if I'm roaming around a mineshaft or something could there be blood arsenal items in a chest?

**Comment by Arcaratus** [comment] 2015-07-07 16:24
Nope

**Comment by tethlah** [comment] 2015-07-08 02:17
Just wanted to make sure, I pregenerated 50k chunks before releasing the server, and I didn't want to have any issues with removing the mod.  Hope you figure it out.

**Comment by Arcaratus** [comment] 2015-07-08 02:29
?

**Closed** 2015-07-22 12:24 UTC
